@startuml

class Start {
  + main
}

class Game_ {
  + Run
}

 Start --> Game_


package Game.Run <<Rectangle>>{
    class Controller {
    + HandleInput
    + ChangeDirection
    }

    class Game {
    + Update
    }

    class Render {
    + Render
    }


    .Game_ --> Controller
    Controller --> Game
    Game --> Render
    Controller::HandleInput --> Controller::ChangeDirection
}

@enduml