@startuml
class Object << general >>
Object <|--- ArrayList

note top of Object : In java, every class\nextends this one.

note "This is a floating note https://plantuml.com/class-diagram" as N1
note "plantuml file.plantuml." as N2
Object .. N2
N2 .. ArrayList

class Foo
note left: On last defined class

@enduml
